configure infrastructure

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -266,7 +266,7 @@ jobs:
            # Your code here
            if grep -q "has been executed successfully," ~/project/backend/migrations_dump.txt
            then
-            curl --insecure https://kvdb.io/16dAiSVamrZg8atoi4XxFi/migration_${CIRCLE_WORKFLOW_ID:0:7} -d '1'
+            curl --insecure https://kvdb.io/JVGxY9HNzCKpAt2UHC97tj/migration_${CIRCLE_WORKFLOW_ID:0:7} -d '1'
            fi 
       - destroy-environment
       - revert-migrations          
@@ -322,7 +322,7 @@ jobs:
       - checkout
       - add_ssh_keys:
           fingerprints:
-            - "fd:68:a5:e7:91:5c:f1:16:97:7c:6e:82:5b:1f:a3:1a"
+            - "af:a4:f7:74:b7:9f:bb:37:60:a0:8a:49:31:d7:db:6f"
       - attach_workspace:
           at: ~/
            # your code here
@@ -348,63 +348,103 @@ jobs:
       - revert-migrations
      # Here's where you will add some code to rollback on failure    
 
-#   smoke-test:
-#     docker:
-#       # Lightweight Docker image 
-#     steps:
-#       # Checkout code from git
-#       - run:
-#           name: Install dependencies
-#           command: |
-#             # your code here
-#       - run:
-#           name: Get backend url
-#           command: |
-#             # your code here
-#       - run:
-#           name: Backend smoke test.
-#           command: |
-#             # your code here
-#       - run:
-#           name: Frontend smoke test.
-#           command: |
-#             # your code here
-#       # Here's where you will add some code to rollback on failure  
+  smoke-test:
+   docker:
+     - image: cimg/base:stable
+     # Lightweight Docker image 
+   steps:
+     # Checkout code from git
+     - checkout
+     - install_nodejs
+     - install_awscli
 
-#   cloudfront-update:
-#     docker:
-#       # Docker image here that supports AWS CLI
-#     steps:
-#       # Checkout code from git
-#       - run:
-#           name: Install dependencies
-#           command: |
-#             # your code here
-#       - run:
-#           name: Update cloudfront distribution
-#           command: |
-#             # your code here
-#       # Here's where you will add some code to rollback on failure  
+     - run:
+         name: Backend smoke test.
+         command: |
+           # your code here
+           BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
+             --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+             --query 'Reservations[*].Instances[*].PublicIpAddress' \
+             --output text)
+           export API_URL=http://${BACKEND_PUBLIC_IP}:3030
+           echo ${BACKEND_PUBLIC_IP}
+           echo backend-${CIRCLE_WORKFLOW_ID:0:7}
+           echo ${API_URL}
+           if curl -s $API_URL/api/status | grep "ok"
+           then
+             exit 0
+           else
+             exit 1
+           fi
+      
+     - run:
+         name: Frontend smoke test.
+         command: |
+           # your code here
+           FRONTEND_WEBSITE=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com
+           echo $FRONTEND_WEBSITE
+           if curl -s $FRONTEND_WEBSITE | grep "Welcome"
+           then 
+             exit 0
+            else
+             exit 1
+            fi 
+     - destroy-environment
+     - revert-migrations
 
-# cleanup:
-#     docker:
-#       # Docker image here
-#     steps:
-#       # Checkout code from git
-#       - run:
-#           name: Get old stack workflow id
-#           command: |
-#             # your code here
-#             export OldWorkflowID="the id here"
-#             export STACKS=[] #put the list of stacks here
-#       - run:
-#           name: Remove old stacks and files
-#           command: |
-#             if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
-#             then
-#               # your code here
-#             fi
-          
+  cloudfront-update:
+    docker:
+     # Docker image here that supports AWS CLI
+     - image: amazon/aws-cli
+     
+   steps:
+     # Checkout code from git
+     - checkout
+     - run:
+         name: Install dependencies
+         command: |
+           # your code here
+           export OldWorkflowID=$(aws cloudformation list-exports --query "Exports[?Name==\`WorkflowID\`].Value" --no-paginate --output text)
+           echo "Old Workflow ID": ${OldWorkflowID}
+           curl https://kvdb.io/JVGxY9HNzCKpAt2UHC97tj/old_workflow_id -d "${OLD_WORKFLOW_ID:0:7}"
+     - run:
+         name: Update cloudfront distribution
+         command: |
+           # your code here
+           aws cloudformation deploy --template-file .circleci/files/cloudfront.yml --stack-name InitialStack --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}"
+     - destroy-environment:
+         workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+     - revert-migrations:
+         workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+     # Here's where you will add some code to rollback on failure
+
+  cleanup:
+   docker:
+     # Docker image here
+     - image: cimg/base:stable
+   steps:
+     # Checkout code from git
+     - checkout
+     - install_awscli
+     - run:
+         name: Get old stack workflow id
+         command: |
+           # your code here
+           export STACKS=($(aws cloudformation describe-stacks --query "Stacks[*].Outputs[?OutputKey=='WorkFlowID'].OutputValue[]" --no-paginate --output text))
+            echo -e "All STACKS (ID): ${STACKS[@]} \n"
+            echo -e "CIRCLE_WORKFLOW_ID: ${CIRCLE_WORKFLOW_ID:0:7} \n"
+            for OldWorkflowID in ${STACKS[@]}; do
+              if [[ "${CIRCLE_WORKFLOW_ID:0:7}" != "${OldWorkflowID}" ]]
+              then
+                echo "------------  Cleaning up ${OldWorkflowID}  ------------"
+                aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
+                aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}"
+                aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}"
+                echo -e "---------------   Cleaning Done ---------------\n\n"
+              else
+                echo -e "----------- Can Not Clean up ${OldWorkflowID} ----------\n\n"
+              fi
+            done
 workflows:
   default:
     jobs:
@@ -431,10 +471,10 @@ workflows:
           requires: [run-migrations]
       - deploy-backend:
           requires: [run-migrations]
-      # - smoke-test:
-      #     requires: [deploy-backend, deploy-frontend]
-      # - cloudfront-update:
-      #     requires: [smoke-test]
-      # - cleanup:
-      #     requires: [cloudfront-update]
+      - smoke-test:
+          requires: [deploy-backend, deploy-frontend]
+      - cloudfront-update:
+          requires: [smoke-test]
+      - cleanup:
+          requires: [cloudfront-update]
       
